version: '3.8'

# docker compose up
# docker compose up --force-recreate --build
services:
  food-produto-app:
    build:
      context: .
    container_name: food-produto-app
    ports:
      - "8080:8080"
    environment:
      - MAVEN_CONFIG=/app/.m2
      - PROFILE=test
    depends_on:
      - localstack
    networks:
      - shared-network
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "./batch-write-items.json:/etc/localstack/init/ready.d/batch-write-items.json"
      - "./run-localstack.sh:/etc/localstack/init/ready.d/init-aws.sh"
#    entrypoint: ["/docker-entrypoint-initaws.d/init.sh"]
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
