name: BDD Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start BDD Tests'
        required: false
        default: 'true'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  execute-bdd-tests:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Set up Docker Compose
        run: sudo apt-get install docker-compose

      - name: Build and start services
        run: docker-compose up --build -d

      - name: Wait for services to be ready
        run: |
          until [ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8080/api/v1/health-check)" -eq 200 ]; do
            echo "Waiting for the service to be ready..."
            sleep 5
          done

      - name: Run BDD tests
        run: mvn test -P bdd-tests

      - name: Generate Cucumber report
        uses: deblockt/cucumber-report-annotations-action@v1.7
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          path: "target/cucumber-reports/cucumber.json"

      - name: Stop and remove services
        run: docker-compose down