name: Unit Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      start:
        description: 'Start Unit Tests'
        required: false
        default: 'true'

# Descomente se precisar de uma nova branch para fazer alterações/testes
#on:
#  push:
#    branches:
#      - feat/add-coverage-info

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  execute-unit-tests:
    uses: ALFAC-Org/github-workflows/.github/workflows/coverage.yaml@main
    secrets: inherit
    permissions: write-all
    with:
      java_version: "17"
      minimum_coverage: "0"
      coverage_results_path: "target/site/jacoco/jacoco.xml"
      jacoco_csv_file: "target/site/jacoco/jacoco.csv"
      test_command: "mvn test -P unit-tests"